# Generated by Django 2.1.4 on 2018-12-27 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('do_list', '0002_note_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='title',
        ),
    ]
