# Generated by Django 2.1.4 on 2018-12-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('do_list', '0003_remove_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
