# Generated by Django 2.1.4 on 2018-12-28 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('do_list', '0004_auto_20181227_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
